#ifndef CLIENT_PROCEDURE(__NAME__, __COMMAND__, __PROTOCOL__)
#define CLIENT_PROCEDURE(__NAME__, __COMMAND__, __PROTOCOL__)
#endif

CLIENT_PROCEDURE(OnConnect, C2S_CONNECT, C2S_DATA_CONNECT)
CLIENT_PROCEDURE(OnVerifyLinks, C2S_VERIFYLINKS, C2S_DATA_VERIFYLINKS)
CLIENT_PROCEDURE(OnAuthAccount, C2S_AUTHACCOUNT, C2S_DATA_AUTHACCOUNT)
CLIENT_PROCEDURE(OnDisconnect, C2S_DISCONNECT, C2S_DATA_DISCONNECT)
CLIENT_PROCEDURE(OnCheckVersion, C2S_CHECKVERSION, C2S_DATA_CHECKVERSION)
CLIENT_PROCEDURE(OnPublicKey, C2S_PUBLICKEY, C2S_DATA_PUBLICKEY)
CLIENT_PROCEDURE(OnServerEnv, C2S_SERVERENV, C2S_DATA_SERVERENV)
CLIENT_PROCEDURE(OnAuthenticate, C2S_AUTHENTICATE, C2S_DATA_AUTHENTICATE)
CLIENT_PROCEDURE(OnUnknown3383, C2S_UNKNOWN3383, C2S_DATA_UNKNOWN3383)
CLIENT_PROCEDURE(OnUnknown5383, C2S_UNKNOWN5383, C2S_DATA_UNKNOWN5383)

#undef CLIENT_PROCEDURE